# Generated by Django 3.1.1 on 2020-09-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Name of company"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="avatars/%Y/%m/%d", verbose_name="Avatar of company"
                    ),
                ),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Name of stock"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="stocks_images/%Y/%m/%d",
                        verbose_name="Image of stock",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description of stock")),
                ("is_free", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "stocks",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="companies.company",
                    ),
                ),
                (
                    "stock",
                    models.ManyToManyField(
                        related_name="addresses", to="companies.Stock"
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
            },
        ),
    ]
