# Generated by Django 3.1.1 on 2020-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="stock",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="addresses", to="companies.Stock"
            ),
        ),
    ]
