# Generated by Django 3.1.1 on 2020-09-02 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_auto_20200902_1931"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "open_work_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Company open work time"
                    ),
                ),
                (
                    "close_work_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Company close work time"
                    ),
                ),
                (
                    "whole_day",
                    models.BooleanField(default=False, verbose_name="24h per day"),
                ),
            ],
            options={
                "db_table": "places",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stock",
            name="date_end",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date end of stock"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AddField(
            model_name="place",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="stock",
            field=models.ManyToManyField(
                blank=True, related_name="places", to="companies.Stock"
            ),
        ),
    ]
