# Generated by Django 3.1.1 on 2020-09-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_contact"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contact",
            table="contacts",
        ),
    ]
