# Generated by Django 3.1.1 on 2020-09-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_auto_20200902_2025"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="stock",
            new_name="stocks",
        ),
    ]
